apiVersion: v1
kind: ConfigMap
metadata:
  name: copilot-config
  namespace: ctrlplane-dev
  labels:
    app: copilot
data:
  server.port: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctrlplane-copilot
  namespace: ctrlplane-dev
  labels:
    app: copilot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: copilot
  template:
    metadata:
      labels:
        app: copilot
    spec:
      containers:
        - name: copilot
          image: quay.io/ctrlplane/copilot:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: copilot-mongo-credentials # kubectl create secret generic copilot-mongo-credentials --from-literal=spring.data.mongodb.uri=mongodb://admin:password@mongo-svc:27017/copilot?authSource=admin
                  key: spring.data.mongodb.uri
                  optional: false
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: copilot-config
                  key: server.port
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: copilot-http
  namespace: ctrlplane-dev
  labels:
    app: copilot
    service: copilot
spec:
  selector:
    app: copilot
  ports:
    - name: copilot-http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
